name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Branche où tu pousses les modifications

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifie le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Déploie sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Répertoire où se trouve index.html
